CREATE TABLE `characters` (
	`id` INT AUTO_INCREMENT NOT NULL,
	`language_id` INT DEFAULT NULL,
	`name` VARCHAR(255) NOT NULL,
	`slug` VARCHAR(255) NOT NULL,
	INDEX `IDX_3A29410E82F1BAF4` (`language_id`),
	UNIQUE INDEX `UNIQ_3A29410E989D9B6282F1BAF4` (`slug`, `language_id`),
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci` ENGINE = InnoDB;

CREATE TABLE `episodes` (
	`id` INT AUTO_INCREMENT NOT NULL,
	`season_id` INT NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`number` INT NOT NULL,
	`slug` VARCHAR(255) NOT NULL,
	INDEX `IDX_7DD55EDD4EC001D1` (`season_id`),
	INDEX `IDX_7DD55EDD989D9B62` (`slug`),
	INDEX `IDX_7DD55EDD5E237E06` (`name`),
	UNIQUE INDEX `UNIQ_7DD55EDD4EC001D1989D9B62` (`season_id`, `slug`),
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci` ENGINE = InnoDB;

CREATE TABLE `languages` (
	`id` INT AUTO_INCREMENT NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`short_code` VARCHAR(3) NOT NULL,
	UNIQUE INDEX `UNIQ_A0D1537917D2FE0D` (`short_code`),
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE `scenarios` (
	`id` INT AUTO_INCREMENT NOT NULL,
	`episode_id` INT NOT NULL,
	`character_id` INT DEFAULT NULL,
	`text` LONGTEXT NOT NULL,
	`line` INT NOT NULL,
	`intro` TINYINT(1) DEFAULT '0' NOT NULL,
	INDEX `IDX_9338D025362B62A0` (`episode_id`),
	INDEX `IDX_9338D0251136BE75` (`character_id`),
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci` ENGINE = InnoDB;

CREATE TABLE `searches` (
	`id` INT AUTO_INCREMENT NOT NULL,
	`input` VARCHAR(255) NOT NULL,
	`slug` VARCHAR(255) NOT NULL,
	`search_time` DATETIME NOT NULL,
	INDEX `IDX_60183819989D9B62` (`slug`),
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE `seasons` (
	`id` INT AUTO_INCREMENT NOT NULL,
	`language_id` INT NOT NULL,
	`number` SMALLINT NOT NULL,
	`year` INT NOT NULL,
	INDEX `IDX_B4F4301C82F1BAF4` (`language_id`),
	UNIQUE INDEX `UNIQ_B4F4301C96901F5482F1BAF4` (`number`, `language_id`),
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci` ENGINE = InnoDB;

ALTER TABLE `characters` ADD CONSTRAINT `FK_3A29410E82F1BAF4` FOREIGN KEY (`language_id`) REFERENCES `languages` (`id`);
ALTER TABLE `episodes` ADD CONSTRAINT `FK_7DD55EDD4EC001D1` FOREIGN KEY (`season_id`) REFERENCES `seasons` (`id`);
ALTER TABLE `scenarios` ADD CONSTRAINT `FK_9338D025362B62A0` FOREIGN KEY (`episode_id`) REFERENCES `episodes` (`id`);
ALTER TABLE `scenarios` ADD CONSTRAINT `FK_9338D0251136BE75` FOREIGN KEY (`character_id`) REFERENCES `characters` (`id`);
ALTER TABLE `seasons` ADD CONSTRAINT `FK_B4F4301C82F1BAF4` FOREIGN KEY (`language_id`) REFERENCES `languages` (`id`);
